### ISSUE TITLE
Not correctly assigning resolution bits

### ISSUE THREAD

**Issue by Wihan** [MaJerle/onewire-uart#3]
Hey @MaJerle 

I think this should be `=` instead of `|=` 

For example 0x60 |= 0x20 would be 0x60 and the configuration would be unchanged.

https://github.com/MaJerle/onewire-uart/blob/662cfffba3e8191c83b8d8ca2fd08e522fcb1c75/onewire_uart/src/devices/ow_device_ds18x20.c#L242-L245

**Comment by MaJerle** [comment]
What is the issue?

**Comment by Wihan** [comment]
The resolution bits won't be properly set because the assignment is |= not = when writing to the scratchpad

**Comment by MaJerle** [comment]
Before I do OR operation, I clear bits.

**Comment by Wihan** [comment]
Ah I somehow missed that, you are right of course.
I've recently been integrating this lib into our system - thank you so much its been great
